### ISSUE TITLE
HSI Damage Font will affect the typhoon font after first hit Hong Kong

### ISSUE THREAD

**Issue by zealitude** [jasonycw/TyphoonTycoon#35]
typhoon font will change after first hit Hong Kong
"maybe" caused by HSI Damage Font Setting

reproduce step: try don't build anything at the beginning

**Comment by vicksonzero** [comment]
try specifying the font right before the ctx draw text call.

**Comment by vicksonzero** [comment]
fixed in vickesonzero now
