### ISSUE TITLE
[Feature Request] Tower description need 

### ISSUE THREAD

**Issue by zealitude** [jasonycw/TyphoonTycoon#6]
User may not know what is the feature of the tower.

**Comment by vicksonzero** [comment]
it turns out there is some description on the button:hover. but jquery is not firing hover when the button is disabled. in short,

the player can see a description only when he can build this tower

**Comment by vicksonzero** [comment]
opened an issue #14 
but there is space to change the description to include more useful messages

**Comment by vicksonzero** [comment]
for example, need to say which is only for sea and which is only for land
