### ISSUE TITLE
Warning Before Earthquake

### ISSUE THREAD

**Issue by vicksonzero** [jasonycw/TyphoonTycoon#8]
AS a gamer I WANT TO have warning before earthquake, SO THAT I have more time preparing for it.
for example, 10 second warning before earthquake comes

**Comment by zealitude** [comment]
the Earthquake frequency is continuously increase, 10s is too long for current setting.
You may need to have a config to control a elapse time between two earthquakes in order to implement this feature.

**Comment by vicksonzero** [comment]
i think it has no direct conflict with 10s warning and increasing frequency of earthquakes. there will be just more than 1 countdown on the field. 

I do foresee that there will be tons of countdown on the field after some time. I think the area of earthquake should increase rather than the frequency.

do u think it will solve the problem? to keep the earthquake frequency almost constant, and increase the earthquake area instead?
